function plotROI(presets, fufaData, roi)

fufaERP = fufaData.erp;
fufaTrials = fufaData.trials;

channels = roi.channels;
channelNames = strjoin(channels, ', ');
channelNumbers = find(ismember(fufaERP.label, channels));
    
% figurePosition = [0, 0];
% figureWidth = 1600;
% figureHeight = 1400;
% roiPlot = figure('Visible', 'on');
% set(roiPlot, 'Position', [figurePosition, figureWidth, figureHeight]);

numTrials = numel(fufaTrials.trial);
for iTrial = 1:numTrials
    fufaTrialPlot = plot(...
        fufaTrials.time{iTrial}, ...
        fufaTrials.trial{iTrial}(channelNumbers, :), ...
        'HandleVisibility', 'off' ...
        );
    trialPlotColour = get(fufaTrialPlot, 'Color');
    set(fufaTrialPlot, 'Color', [trialPlotColour, 0.25]);
    hold on
end

plot(...
    fufaERP.time, ...
    fufaERP.avg(channelNumbers, :), ...
    'LineWidth', 2.5, ...
    'Color', [0, 0.447, 0.741], ...
    'DisplayName', 'FuFA' ...
    );

line(...
    [roi.time.start, roi.time.end], ...
    [roi.meanAmplitude, roi.meanAmplitude], ...
    'Color', 'r', ...
    'LineWidth', 2.5, ...
    'DisplayName', 'ROI' ...
    );
xline(roi.time.start, '--', 'LineWidth', 2, 'Color', 'r', 'HandleVisibility', 'off')
xline(roi.time.end, '--', 'LineWidth', 2, 'Color', 'r', 'HandleVisibility', 'off')

yline(0, 'LineStyle', '--', 'LineWidth', 1.5, 'HandleVisibility', 'off')
xline(...
    presets.preprocessing.baselinewindow(1), ...
    'LineStyle', '--', ...
    'LineWidth', 1.5, ...
    'HandleVisibility', 'off' ...
    );
xline(...
    presets.preprocessing.baselinewindow(2), ...
    'LineStyle', '--', ...
    'LineWidth', 1.5, ...
    'HandleVisibility', 'off' ...
    );

xlabel('Time (seconds)')
ylabel('Amplitude (\muV)')
xlim([-0.5, 1.5])
ylim([-35, 35])
xticks(-0.5:0.1:1.5)
yticks(-35:5:35)
titleText = sprintf('Region of Interest (ROI) from Fully-Flattened Average (FuFA) \n (%s)', channelNames);
title(titleText)
legend
grid on
box off

hold off